creating the smoke test job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -333,43 +333,76 @@ jobs:
       - destroy-environment
       - revert-migrations
 
-#   smoke-test:
-#     docker:
-#       # Lightweight Docker image
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             # your code here
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure
+  smoke-test:
+    docker:
+      # Lightweight Docker image
+      image: cimg/base:stable
+    steps:
+      - checkout
+      - install_nodejs
+      - install_awscli
+      # Checkout code from git
+      # - run:
+      #     name: Get backend url
+      #     command: |
 
-#   cloudfront-update:
-#     docker:
-#       # Docker image here that supports AWS CLI
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Update cloudfront distribution
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure
+      - run:
+          name: Backend smoke test.
+          command: |
+            # Fetch and prepare the BACKEND_IP env var
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+            --filters Name=tag:Name,Values-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --output text
+            )
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo ${BACKEND_PUBLIC_IP}
+            echo ${CIRCLE_WORKFLOW_ID:0:7}
+            echo ${API_URL}
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+                exit 0
+            else
+                exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website${AWS_DEFAULT_REGION}.amazonaws.com"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+               
+              exit 1
+            else
+              exit 1
+            fi
+      # Here's where you will add some code to rollback on failure
+
+  cloudfront-update:
+      docker:
+        image: amazon/aws-cli
+      steps:
+        - checkout
+        - run:
+            name: Install dep / Save Old Workflow ID to kvdb.io 
+            command: |
+              export OLD WORKFLOW_ID=$(aws cloud formation \
+              list-exports --query "Exports [?Name==\"WorkflowID\`].Value" \
+              --no-paginate --output text)
+              echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
+              curl https://kvdb.io/8iHBPvVVJXtSVD6Wu24r4c/old_workflow_id -d "${OLD_WORKFLOW_ID}"
+        - run:
+              name: Update cloudfront distribution
+              command: |
+                aws cloudformation deploy \
+                --template-file .circleci/files/cloudfront.yml \
+                --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+                --stack-name InitialStack
+          - destroy-environment
+          - revert-migrations
+              # Here's where you will add some code to rollback on failure
 
 # cleanup:
 #     docker:
@@ -416,9 +449,9 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update:
-      #     requires: [smoke-test]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
+      - cloudfront-update:
+          requires: [smoke-test]
       # - cleanup:
       #     requires: [cloudfront-update]
